spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/back
    username: postgres
    password: asd
    validationQuery: SELECT 1
    testOnBorrow: true
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      show_sql: true
      format_sql: true
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
